"""The rotation token a pairing's QR carries, and the one check made on it.

WHAT IT IS FOR. The QR on the pairing page encodes the app link with this
token in its ``qr`` parameter, and the page replaces the image every two
seconds. ``POST /scan`` refuses a token outside a twelve-second window, so a
QR that travels anywhere slower than a camera -- a screenshot in an email, an
image on a forum, a photo passed along later -- is refused by the time it
arrives. That is the whole of what rotation buys. It does not stop a live
relay or a phishing link to the genuine page; ``dev-docs/qr-page-spec.md``
says so in its "What this does not fix" section and this module does not
pretend otherwise.

THE CONSTRUCTION. ``HMAC-SHA256(qr_secret, user_code || slot)``, truncated to
16 bytes and written as unpadded base64url. ``qr_secret`` is 32 random bytes
per pairing, generated by the device-code store and never sent anywhere, so a
token for one pairing says nothing about another. The input is fixed width --
six ASCII bytes of ``user_code`` then the slot as eight big-endian bytes -- so
no two ``(user_code, slot)`` pairs share an encoding.

THE WINDOW. Five slots back and one forward. Ten seconds back covers the
camera, the app launch, the assertion fetch and the request itself; one slot
forward covers clock skew between replicas. Anything further forward is
refused as INVALID rather than STALE, because only a verifying MAC for a slot
this server has already passed earns the distinct ``qr_stale`` answer.

A TOKEN IS REPLAYABLE INSIDE ITS WINDOW. That is harmless because the first
scan of a pairing wins (``claim_scan`` in ``postern_core.auth.device_codes``)
and any later scan by another customer is a ``scan_conflict``.

Every number here is a code constant with no setting, on purpose: the window
is a security property derived from the page's two-second poll, and an
operator knob would be a way to widen it without reading this.
"""

from __future__ import annotations

import base64
import enum
import hashlib
import hmac
import math
import re

#: The width of one slot, matching the page's two-second poll.
SLOT_SECONDS = 2

#: How many slots before the current one still verify.
SLOTS_BACK = 5

#: How many slots after the current one still verify, for replica clock skew.
SLOTS_FORWARD = 1

#: How much of the HMAC-SHA256 output the token carries.
MAC_BYTES = 16

#: The stored pairing code's width in bytes. Every stored code is six
#: characters from ``23456789ABCDEFGHJKLMNPQRSTUVWXYZ``.
USER_CODE_BYTES = 6

#: The slot as it may appear in a token: ASCII digits only, at most 19 of them
#: so the value always fits the eight bytes the MAC input reserves for it, and
#: no leading zero unless the slot is exactly ``0``: ``token_for`` never writes
#: one, so a zero-prefixed spelling is a second text for the same token.
_SLOT_TEXT = re.compile(r"0|[1-9][0-9]{0,18}")

#: The MAC as it may appear: exactly the unpadded base64url of 16 bytes.
_MAC_TEXT = re.compile(r"[A-Za-z0-9_-]{22}")


class QrVerdict(enum.Enum):
    """What ``verify_token`` concluded about a presented token."""

    #: A genuine MAC for a slot inside the window.
    VALID = "valid"
    #: A genuine MAC for a slot older than the window. The trace of a relay.
    STALE = "stale"
    #: Anything else: malformed, forged, for another pairing, or from the future.
    INVALID = "invalid"


def slot_at(unix_time: float) -> int:
    """The slot a POSIX instant falls in."""
    return math.floor(unix_time / SLOT_SECONDS)


def message_for(user_code: str, slot: int) -> bytes:
    """The fixed-width MAC input. Raises ``ValueError`` for a malformed code."""
    encoded = user_code.encode("ascii")
    if len(encoded) != USER_CODE_BYTES:
        raise ValueError(f"a pairing code is {USER_CODE_BYTES} ASCII bytes, got {len(encoded)}")
    return encoded + slot.to_bytes(8, "big")


def _digest(qr_secret: bytes, user_code: str, slot: int) -> bytes:
    return hmac.new(qr_secret, message_for(user_code, slot), hashlib.sha256).digest()[:MAC_BYTES]


def mac_for(qr_secret: bytes, user_code: str, slot: int) -> str:
    """The truncated MAC, as unpadded base64url."""
    encoded = base64.urlsafe_b64encode(_digest(qr_secret, user_code, slot))
    return encoded.rstrip(b"=").decode("ascii")


def token_for(qr_secret: bytes, user_code: str, slot: int) -> str:
    """The token the QR carries for ``slot``: ``<slot>.<mac>``."""
    return f"{slot}.{mac_for(qr_secret, user_code, slot)}"


def verify_token(qr_secret: bytes, user_code: str, token: str, now_slot: int) -> QrVerdict:
    """Check a presented token against a stored pairing.

    Never raises on caller input: every malformed shape is ``INVALID``. An
    empty ``qr_secret`` -- a record written before this module existed --
    verifies nothing, so such a pairing is unscannable rather than scannable
    with the empty key.

    A token has exactly one accepted spelling, the one ``token_for`` writes.
    The MAC is compared as text, against ``mac_for`` recomputed for the
    presented slot, and not as decoded bytes: the last of its 22 characters
    carries 2 significant bits and a decoder ignores the other 4, so a byte
    comparison would accept 16 spellings of one MAC. The slot refuses a
    leading zero for the same reason. Anything that later logs, dedupes or
    rate-limits by token string can therefore not be evaded by re-spelling.
    """
    if not qr_secret:
        return QrVerdict.INVALID
    slot_text, dot, mac_text = token.partition(".")
    if not dot or not _SLOT_TEXT.fullmatch(slot_text) or not _MAC_TEXT.fullmatch(mac_text):
        return QrVerdict.INVALID
    slot = int(slot_text)
    if slot > now_slot + SLOTS_FORWARD:
        return QrVerdict.INVALID
    try:
        expected = mac_for(qr_secret, user_code, slot)
    except ValueError:
        return QrVerdict.INVALID
    if not hmac.compare_digest(mac_text.encode("ascii"), expected.encode("ascii")):
        return QrVerdict.INVALID
    if slot < now_slot - SLOTS_BACK:
        return QrVerdict.STALE
    return QrVerdict.VALID
