"""Schema-drift gate: ``Base.metadata`` (the models) against the migration chain at `head`.

`alembic check` runs `autogenerate` against a live database already migrated
to `head` and raises if the resulting diff is non-empty -- i.e. if the models
describe a schema the migration chain does not actually produce. It is the
only thing in this repo that would have caught `0de54913a8b2` declaring
`sa.JSON()` while `AuditEntry.risk_signals` declared `JSONB`: same column
name, same nullability, different type, and `alembic check`'s online path
compares types (see `migrations/env.py::do_run_migrations`, which also turns
on `compare_server_default` so a `server_default` edited on only one side is
caught too). That mismatch shipped and was found weeks later by an audit
instead of by CI, because `Makefile:60-71` carried this check as a
standalone `migrations` target excluded from `ci` -- see that comment for
the excluded state's own reasoning, and its "no longer holds" update for why
that reasoning stopped applying once `test` started a real Postgres for
`tests/test_store_consents.py`.

Three design decisions, made here rather than guessed:

1. **A pytest test reusing `pg_url`, not a new container or a Make target.**
   `pg_url` (session-scoped, in `tests/conftest.py`) already starts the same
   `testcontainers` Postgres the rest of the suite uses and already runs the
   full chain to `head` via `command.upgrade` before yielding -- exactly the
   database state `alembic check` needs, with no second container and no
   second migration run. A Make target calling `docker compose up` would
   duplicate that container lifecycle and skip logic for no benefit, and
   would run outside pytest's `-rs` reporting that names every skip.

2. **Docker-down degrades to `pg_url`'s existing skip, not a new one.**
   `pg_url` pings the Docker daemon itself before `PostgresContainer` gets a
   chance to, and calls `pytest.skip` with the reason inline if that ping
   fails -- see its docstring. This test takes a `pg_url` fixture argument
   like the other 146 database-backed tests already do, so it inherits that
   skip for free: a Docker-less laptop sees
   `SKIPPED [...] Docker is not reachable, skipping database-backed tests:
   ...` under `-rs`, never a silent pass and never a bare
   `docker.errors.DockerException` traceback.

3. **The `migrations` Make target stays**, with its comment corrected. It
   predates this file and is no longer the only thing running `alembic
   check`, but it is still the faster manual loop for the one case this test
   cannot serve: checking drift against a database an operator points it at
   explicitly (a long-lived dev Postgres via `docker compose up -d db`,
   a staging replica, anything that is not the disposable container `test`
   starts and tears down per session) without running the rest of the suite
   first. What changed is only that it is no longer *load-bearing* for CI:
   the drift check now runs, and blocks, inside `make ci` through this file.

Deliberately synchronous. `pg_url` itself is sync for the same reason its
own docstring gives: the online path in `migrations/env.py` ends in
`asyncio.run()` (`run_migrations_online`), which `command.check` reaches the
same way `command.upgrade` does (`ScriptDirectory.run_env()` execs
`migrations/env.py` either way). Calling either from inside an `async def`
test would raise `RuntimeError: asyncio.run() cannot be called from a
running event loop` under this repo's `asyncio_mode = "auto"`, which wraps
every `async def` test in one already.
"""

import pytest
from alembic import command
from alembic.config import Config
from alembic.util import AutogenerateDiffsDetected


def test_migration_chain_matches_models(pg_url: str) -> None:
    """Fails, naming the diff, when the migration chain at `head` does not
    reproduce what `packages/postern-core/src/postern_core/store/models.py`
    declares."""
    cfg = Config("alembic.ini")
    cfg.set_main_option("sqlalchemy.url", pg_url)
    try:
        command.check(cfg)
    except AutogenerateDiffsDetected as exc:
        pytest.fail(
            "schema drift detected between "
            "packages/postern-core/src/postern_core/store/models.py and the "
            f"migration chain at head -- a migration is missing or wrong: {exc}"
        )
