"""Adapts the internal minter to the TokenMinter protocol BackendClient calls.

Read audiences only. `payments.svc` is deliberately absent: asking this minter
for a write audience raises rather than minting a token with a guessed scope.
That is a second, independent barrier to the key split. Even holding the right
key, a write token from here would carry the wrong scope, and Istio matches on
claims as well as on the signature.

ZT-1 — Continuous authorization: every mint checks the revocation list and
the jti replay cache before issuing a token. A revoked session dies at mint,
not at next refresh (ZT-1 acceptance criterion).

See ``postern_core.auth.revocation.RevocationList`` for the revocation API.
"""

from __future__ import annotations

import time
from collections import OrderedDict
from typing import TYPE_CHECKING

from postern_core.auth.internal_jwt import InternalTokenMinter
from postern_core.identity import CustomerRef

if TYPE_CHECKING:
    from postern_core.auth.revocation import RevocationList

READ_SCOPES = {
    "accounts.svc": "accounts:read",
    "transactions.svc": "transactions:read",
    "cards.svc": "cards:read",
}


class JtiReplayCache:
    """In-memory jti replay cache covering the token lifetime.

    Tracks every ``jti`` minted since startup and evicts entries older than
    the token lifetime. A duplicate jti within the window raises so the
    caller can reject the request (ZT-1, A10).

    Thread-safe enough for FastMCP's in-process test client (single-threaded
    async). Not safe across processes — that requires a shared store.
    """

    def __init__(self, *, max_age_seconds: float = 60.0) -> None:
        self._cache: OrderedDict[str, float] = OrderedDict()
        self._max_age_seconds = max_age_seconds

    def add(self, jti: str) -> None:
        """Record a jti. Raises ``ValueError`` if the jti was seen recently."""
        now = time.monotonic()
        # Evict expired entries first
        while self._cache and now - next(iter(self._cache.values())) > self._max_age_seconds:
            self._cache.popitem(last=False)

        if jti in self._cache:
            raise ValueError(f"jti replay detected: {jti}")

        self._cache[jti] = now

    def clear(self) -> None:
        """Remove all entries. Useful for tests."""
        self._cache.clear()

    @property
    def size(self) -> int:
        """Number of active entries (for testing)."""
        return len(self._cache)


class ReadTokenMinter:
    """Wraps ``InternalTokenMinter`` with ZT-1 continuous authorization.

    Every call checks the revocation list (if provided) and the jti replay
    cache before minting. A revoked session dies at mint, not at next refresh.

    Args:
        minter: The underlying ``InternalTokenMinter`` that signs tokens.
        revocation_list: Optional ``RevocationList`` for push-based revocation.
            When provided, the minter checks session, customer+client, and
            kill-switch scopes before issuing a token.
        jti_cache: Optional ``JtiReplayCache`` for A10 (token replay prevention).
            When provided, duplicate jtis within the token lifetime raise.
    """

    def __init__(
        self,
        minter: InternalTokenMinter,
        *,
        revocation_list: RevocationList | None = None,
        jti_cache: JtiReplayCache | None = None,
    ) -> None:
        self._minter = minter
        self._revocation_list = revocation_list
        self._jti_cache = jti_cache

    def __call__(self, customer: CustomerRef, audience: str) -> str:
        scope = READ_SCOPES[audience]

        # ZT-1: check revocation before minting
        if self._revocation_list is not None:
            # Build a minimal claims dict for the revocation check.
            # We don't have the jti yet (it's generated by mint()), so we
            # check customer+client and kill-switch scopes. The session scope
            # (jti) is checked after mint via the replay cache.
            # audience maps to client_id in revocation terms: a customer+audience
            # pair is the internal equivalent of a customer+client revocation.
            claims: dict[str, str | None] = {
                "sub": customer.value,
                "client_id": audience,
            }
            if self._revocation_list.is_revoked(claims):
                raise PermissionError(
                    f"customer {customer.value} is revoked for audience {audience}"
                )

        token = self._minter.mint(subject=customer, audience=audience, scope=scope)

        # ZT-1 A10: check jti replay cache after mint
        if self._jti_cache is not None:
            # Extract jti from the token to check for replays.
            # We decode just enough to get the jti — the signature is already
            # verified by InternalTokenMinter's caller (minter_probe).
            from joserfc import jwt as _jwt
            from joserfc.jwk import KeySet as _KeySet

            keyset = _KeySet.import_key_set(self._minter.key_source.public_jwks())
            decoded = _jwt.decode(token, keyset, algorithms=["RS256"])
            jti: str = decoded.claims["jti"]
            self._jti_cache.add(jti)

        return token
